-- AUTO-GENERATED MOUNTAIN INSERTS --

INSERT INTO copper_lifts (lift_name, open_closed, lift_type) VALUES
('Super Bee', 'True', 'six_person'),
('Mountain Chief', 'True', 'double'),
('Black Jack', 'True', 'double'),
('Three Bears', 'True', 'triple'),
('Storm King', 'True', 'surface'),
('Resolution', 'True', 'triple'),
('Sierra', 'True', 'triple'),
('Rendezvous', 'True', 'triple'),
('Celebrity Ridge', 'False', 'surface'),
('Pitchfork', 'True', 'double'),
('Gem', 'True', 'surface'),
('Easy Rider', 'True', 'carpet'),
('American Eagle', 'True', 'telemix'),
('Tubing Hill', 'True', 'carpet'),
('Alpine', 'True', 'double'),
('Woodward Express', 'True', 'quad'),
('Timberline Express', 'True', 'six_person'),
('Slingshot/Glide', 'True', 'carpet'),
('Rugrat', 'True', 'carpet'),
('Lumberjack', 'True', 'triple'),
('Kokomo Express', 'True', 'quad'),
('Excelerator', 'True', 'quad'),
('American Flyer', 'True', 'six_person');

INSERT INTO copper_runs (run_name, open_closed, groomed, difficulty) VALUES
('17 Glade', 'True', 'False', '3'),
('American Flyer', 'True', 'False', '2'),
('Bittersweet (L)', 'True', 'False', '2'),
('Bittersweet (U)', 'True', 'False', '2'),
('Bouncer (L)', 'True', 'False', '2'),
('Bouncer (U)', 'True', 'False', '2'),
('Brennan''s Grin', 'True', 'False', '3'),
('Bridgeway', 'True', 'False', '1'),
('CDL''s Trail #20', 'True', 'False', '3'),
('Cache Glades', 'True', 'False', '3'),
('Carefree (L)', 'True', 'False', '2'),
('Carefree (U)', 'True', 'False', '1'),
('Collage (L)', 'True', 'False', '2'),
('Collage (U)', 'True', 'False', '2'),
('Copperopolis', 'True', 'False', '2'),
('Coppertone', 'True', 'False', '1'),
('Easy Road', 'True', 'False', '1'),
('Easy Road Traverse', 'True', 'False', '1'),
('Fair Play', 'True', 'False', '2'),
('Family Cross', 'True', 'False', '1'),
('Foul Play', 'True', 'False', '2'),
('Frank''s Fave', 'True', 'False', '2'),
('Hallelujah', 'True', 'False', '3'),
('High Point', 'True', 'False', '1'),
('High Point Bypass', 'True', 'False', '1'),
('I-Dropper', 'True', 'False', '2'),
('Indian Ridge', 'False', 'False', '3'),
('Leap Frog (L)', 'True', 'False', '1'),
('Leap Frog (U)', 'True', 'False', '1'),
('Liberty', 'True', 'False', '2'),
('Looking Glass', 'True', 'False', '3'),
('Loverly', 'True', 'False', '1'),
('Lower Enchanted Forest', 'True', 'False', '4'),
('Main Vein', 'True', 'False', '2'),
('Mine Dump', 'True', 'False', '3'),
('Nastar', 'False', 'False', '2'),
('Ptarmigan', 'True', 'False', '2'),
('Rhapsody', 'True', 'False', '2'),
('Sail Away Glades', 'True', 'False', '3'),
('See and Ski', 'True', 'False', '1'),
('Skid Road', 'True', 'False', '2'),
('Slip Not', 'True', 'False', '3'),
('Sluice', 'True', 'False', '1'),
('Upper Looking Glass', 'True', 'False', '3'),
('Upper Sluice', 'True', 'False', '2'),
('Ute Overlook', 'True', 'False', '3'),
('Bucksaw', 'True', 'False', '2'),
('Clear Cut', 'True', 'False', '2'),
('Copperfield', 'True', 'False', '2'),
('Easy Feelin''', 'True', 'False', '1'),
('Fairway', 'True', 'False', '1'),
('Hidden Vein', 'True', 'False', '1'),
('I-Way', 'True', 'False', '1'),
('Jackstraw Trees', 'True', 'False', '2'),
('Jacque''s Pique', 'True', 'False', '2'),
('Kokomo Glade', 'True', 'False', '1'),
('Little Burn', 'True', 'False', '2'),
('Log Chute', 'False', 'False', '1'),
('Loverly Lane', 'True', 'False', '1'),
('Lyman Lane', 'True', 'False', '1'),
('Minor Matter', 'True', 'False', '1'),
('Pinecone Alley', 'True', 'False', '2'),
('Prospector', 'True', 'False', '1'),
('Roundabout (L)', 'True', 'False', '1'),
('Roundabout (U)', 'True', 'False', '1'),
('Scooter', 'True', 'False', '1'),
('Snodeal', 'True', 'False', '2'),
('Soliloquy', 'True', 'False', '1'),
('Tempo', 'True', 'False', '2'),
('The Moz', 'True', 'False', '2'),
('Timber Road', 'True', 'False', '1'),
('Vein Glory (L)', 'True', 'False', '1'),
('Vein Glory (U)', 'True', 'False', '1'),
('West Ten Mile', 'True', 'False', '1'),
('Windsong', 'True', 'False', '2'),
('Woodwinds', 'True', 'False', '1'),
('Woodwinds Traverse', 'True', 'False', '1'),
('Andy''s Encore (L)', 'True', 'False', '2'),
('Andy''s Encore (U)', 'True', 'False', '2'),
('Bee Traverse', 'True', 'False', '3'),
('Black Bear Glade', 'True', 'False', '4'),
('Far East', 'True', 'False', '3'),
('Formidable', 'True', 'False', '3'),
('Free Fall Glade', 'True', 'False', '4'),
('Home Run', 'True', 'False', '2'),
('Oh No (L)', 'True', 'False', '2'),
('Oh No (U)', 'True', 'False', '2'),
('Ore Deal', 'True', 'False', '3'),
('Overlode', 'True', 'False', '3'),
('Rosi''s Run', 'True', 'False', '3'),
('Slot Car Track', 'True', 'False', '2'),
('Too Much', 'True', 'False', '3'),
('Treble Cliff', 'True', 'False', '3'),
('Triple Treat', 'True', 'False', '3'),
('West Encore', 'True', 'False', '2'),
('EZ Rider/Learning Area', 'True', 'False', '1'),
('Green Acres', 'True', 'False', '1'),
('Buzzard''s Alley', 'True', 'False', '4'),
('Colman''s Retreat', 'True', 'False', '3'),
('Endeavor', 'True', 'False', '3'),
('Far West', 'True', 'False', '3'),
('Gold Digger', 'True', 'False', '3'),
('Guthrie�s Chute', 'True', 'False', '3'),
('Kaboom', 'True', 'False', '3'),
('Little Trees', 'False', 'False', '3'),
('Revenge (L)', 'True', 'False', '3'),
('Revenge (U)', 'True', 'False', '3'),
('Timber Ridge', 'True', 'False', '2'),
('Union Gap', 'True', 'False', '2'),
('Union Meadows', 'True', 'False', '3'),
('Union Park', 'True', 'False', '1'),
('Union Peak', 'True', 'False', '3'),
('Wheeler Creek', 'True', 'False', '1'),
('Atlantic Cornice', 'False', 'False', '4'),
('Bariloche', 'True', 'False', '3'),
('Boardwalk', 'True', 'False', '3'),
('Cabin Chute', 'True', 'False', '3'),
('Calendar Chute', 'True', 'False', '4'),
('Cornice Chute', 'True', 'False', '4'),
('Double Zero', 'True', 'False', '4'),
('Drain Pipe', 'True', 'False', '4'),
('Hallelujah Ridge', 'True', 'False', '3'),
('Highline', 'True', 'False', '3'),
('Hodson''s Cut', 'True', 'False', '3'),
('Lillie G (U)', 'True', 'False', '4'),
('Lillie G Traverse', 'True', 'False', '3'),
('Marvin Garden', 'True', 'False', '3'),
('Pacific Cornice', 'False', 'False', '4'),
('Park Place', 'True', 'False', '3'),
('Patrol Chute', 'True', 'False', '4'),
('Sawtooth', 'True', 'False', '3'),
('So Fine', 'False', 'False', '4'),
('Spaulding Glades', 'True', 'False', '3'),
('Spaulding Ridge', 'True', 'False', '3'),
('Triple Zero', 'True', 'False', '4'),
('Upper Enchanted Forest', 'True', 'False', '4'),
('Boulderado', 'False', 'False', '5'),
('Buffalo Stampede', 'True', 'False', '5'),
('Denverite', 'True', 'False', '5'),
('Falcon Alley', 'True', 'False', '5'),
('Lower Boulderado Hike Back', 'False', 'False', '5'),
('Ram''s Run', 'True', 'False', '5'),
('Summit Stash', 'True', 'False', '3'),
('The Springs', 'True', 'False', '5'),
('The Taco/Curecanti', 'True', 'False', '5'),
('Valentine''s', 'False', 'False', '5'),
('Western Slope', 'True', 'False', '5'),
('Alicante', 'True', 'False', '3'),
('Bradley''s Plunge', 'False', 'False', '5'),
('Colorado Boulevard', 'True', 'False', '2'),
('Golden Crest', 'False', 'False', '3'),
('Iron Mask', 'False', 'False', '5'),
('Julie''s Vision', 'False', 'False', '3'),
('Lallarookn', 'False', 'False', '4'),
('Lillie G (L)', 'False', 'False', '3'),
('Matchless', 'True', 'False', '3'),
('Otto Bahn', 'True', 'False', '2'),
('Rattler', 'True', 'False', '3'),
('Schaefer''s', 'False', 'False', '5'),
('Six Shooter', 'True', 'False', '3'),
('Central Park on Loverly', 'True', 'False', '1'),
('Miner�s Progression Park on Roundabout', 'True', 'False', '1'),
('Family Cross on High Point', 'True', 'False', '1'),
('Green Acres Progression Park', 'True', 'False', '1'),
('Koko''s Progression Park on Roundabout', 'True', 'False', '1'),
('Peace Park on Vein Glory', 'True', 'False', '1'),
('Pipe Dream on Vein Glory', 'True', 'False', '1'),
('Red''s Backyard on Loverly Lane', 'True', 'False', '1'),
('Start Park at Easy Rider', 'True', 'False', '1'),
('Superpipe on Main Vein', 'True', 'False', '1'),
('Farleys (L)', 'True', 'False', '2'),
('Farleys (U)', 'True', 'False', '2'),
('Farleys Connect', 'True', 'False', '2'),
('Golf Course Loops', 'False', 'False', '1'),
('Guller Creek', 'True', 'False', '1'),
('West Ten Mile', 'True', 'False', '1'),
('Aerie/PHQ (Route 1)', 'True', 'False', '2'),
('Carefree/Highpoint (Route 2)', 'True', 'False', '1'),
('Chickaree Way (Route 3)', 'True', 'False', '1'),
('Copperfield (Route 5)', 'True', 'False', '2'),
('Lewis Ranch (Route 4)', 'True', 'False', '1'),
('Soliloquy (Route 6)', 'True', 'False', '1'),
('Union Meadows (Route 7)', 'True', 'False', '3'),
('West Ten Mile (Route 8)', 'True', 'False', '1'),
('2 Bucks', 'False', 'False', '3'),
('Blue Oso', 'False', 'False', '2'),
('Gopher It', 'False', 'False', '2'),
('Loose Moose', 'False', 'False', '2'),
('Lower Red Tail', 'False', 'False', '2'),
('Pump Track', 'False', 'False', '1'),
('Red Tail', 'False', 'False', '2'),
('Upper Fawn-tastic', 'False', 'False', '1'),
('Upper Red Tail', 'False', 'False', '2'),
('Kid�s Arena', 'True', 'False', '1');

INSERT INTO eldora_lifts (lift_name, open_closed, lift_type) VALUES
('Caribou', 'True', 'double'),
('Little Hawk', 'False', 'double'),
('Sundance', 'True', 'double'),
('Corona', 'True', 'quad'),
('Alpenglow', 'True', 'six_person'),
('Sunkid', 'True', 'carpet'),
('Indian Peaks', 'True', 'quad'),
('Race', 'False', 'surface'),
('EZ', 'True', 'triple'),
('Tenderfoot', 'True', 'carpet');

INSERT INTO eldora_runs (run_name, open_closed, groomed, difficulty) VALUES
('Powderhorn Glades', 'True', 'False', '4'),
('Sidewinder', 'True', 'False', '2'),
('Placer Glades', 'False', 'False', '5'),
('Lower Diamondback', 'True', 'False', '2'),
('Lower Ambush', 'True', 'False', '2'),
('Liftline', 'True', 'False', '5'),
('City Lights', 'True', 'False', '2'),
('Ambush', 'True', 'False', '4'),
('Windmill', 'True', 'False', '2'),
('Sunset', 'True', 'False', '2'),
('Summer Road', 'True', 'False', '1'),
('Psychopath', 'False', 'False', '3'),
('Upper Around the Horn', 'True', 'False', '2'),
('Powderhorn', 'True', 'False', '2'),
('Mary''s Way', 'True', 'False', '3'),
('La Belle Dame', 'True', 'False', '2'),
('Klondike', 'True', 'False', '2'),
('Jolly Jug Glades', 'False', 'False', '4'),
('Jolly Jug', 'True', 'False', '2'),
('International', 'True', 'False', '2'),
('Hot Dog Alley', 'True', 'False', '2'),
('Hornblower', 'True', 'False', '2'),
('Dream & Scream', 'True', 'False', '2'),
('Pipeline', 'True', 'False', '2'),
('Reel It In', 'True', 'False', '2'),
('Pipeline Uphill Route', 'True', 'False', '2'),
('Frontside Uphill Route', 'True', 'False', '2'),
('Early Uphill Route', 'True', 'False', '2'),
('Backside Uphill Route', 'True', 'False', '3'),
('Wolf Tongue', 'True', 'False', '3'),
('West Ridge', 'True', 'False', '5'),
('Wayback', 'True', 'False', '2'),
('Salto Glades', 'True', 'False', '5'),
('Red Tail', 'True', 'False', '3'),
('Crewcut', 'True', 'False', '2'),
('Muleshoe', 'True', 'False', '3'),
('Moose Glades', 'True', 'False', '5'),
('Lower Around the Horn', 'True', 'False', '2'),
('Gully Glades', 'True', 'False', '4'),
('Corona Road', 'True', 'False', '2'),
('Corona', 'True', 'False', '3'),
('Cascade', 'True', 'False', '3'),
('Brian''s Glades', 'True', 'False', '4'),
('Alpenhorn', 'True', 'False', '3'),
('Upper Diamondback', 'True', 'False', '3'),
('Ja Sure', 'False', 'False', '2'),
('Twin Twisted Tree', 'False', 'False', '2'),
('Stadium', 'False', 'False', '1'),
('Snowcat', 'False', 'False', '1'),
('Sawmill', 'False', 'False', '3'),
('Roller Coaster', 'False', 'False', '2'),
('Porcupine Park Loop', 'False', 'False', '3'),
('Phoebe Snow Loop', 'False', 'False', '1'),
('Peterson''s Return', 'False', 'False', '2'),
('Mill Iron', 'False', 'False', '2'),
('Meadows Loop', 'False', 'False', '1'),
('Jenny Creek Loop', 'False', 'False', '1'),
('Woodcutter', 'False', 'False', '3'),
('Gandy Dancer', 'False', 'False', '3'),
('For Pete''s Sake', 'False', 'False', '2'),
('Dixie', 'False', 'False', '1'),
('Deadman''s Gulch', 'False', 'False', '2'),
('Cheaters Corner', 'False', 'False', '2'),
('Buckeye Basin Loop', 'False', 'False', '2'),
('Bogwaun', 'False', 'False', '2'),
('Beaver''s Revenge', 'False', 'False', '2'),
('Antelope Creek', 'False', 'False', '3'),
('Annie B', 'False', 'False', '2'),
('Ryder''s', 'True', 'False', '1'),
('Corona Traverse', 'True', 'False', '2'),
('Challenge', 'False', 'False', '3'),
('Cannonball Run', 'False', 'False', '3'),
('Bonanza', 'True', 'False', '2'),
('4 O''Clock', 'True', 'False', '2'),
('Upper Bunnyfair', 'True', 'False', '2'),
('Uncle Bob''s', 'True', 'False', '1'),
('Trick Ditch', 'True', 'False', '2'),
('Sunkid', 'True', 'False', '1'),
('Sundance', 'True', 'False', '2'),
('17th Avenue', 'False', 'False', '1'),
('Little Hawk', 'True', 'False', '1'),
('Gabor''s', 'True', 'False', '2'),
('Fun Zone', 'True', 'False', '1'),
('Fun Gully', 'True', 'False', '1'),
('Foxtail', 'True', 'False', '1'),
('Easyway', 'True', 'False', '1'),
('EZ LIftline', 'True', 'False', '2'),
('Chute', 'True', 'False', '2'),
('Bunnyfair', 'True', 'False', '1'),
('Zarlengo Loop', 'False', 'False', '2');

INSERT INTO steamboat_lifts (lift_name, open_closed, lift_type) VALUES
('Steamboat Gondola', 'True', 'Gondola'),
('Wild Blue Gondola Lower', 'True', 'Gondola'),
('Wild Blue Gondola Upper', 'True', 'Gondola'),
('Bar-UE', 'False', 'Double'),
('Bashor', 'True', 'Double'),
('Burgess Creek', 'True', 'Triple Chair'),
('Christie Peak Express', 'True', 'High-Speed 6 Chair'),
('Elkhead Express', 'True', 'High-Speed Quad'),
('Four Points', 'True', 'Triple Chair'),
('Greenhorn Ranch Express', 'False', 'High-Speed Quad'),
('Mahogany Ridge Express', 'False', 'High-Speed Quad'),
('Morningside', 'False', 'Triple Chair'),
('Pony Express', 'False', 'High-Speed Quad'),
('South Peak', 'True', 'Triple Chair'),
('Storm Peak Express', 'True', 'High-Speed Quad'),
('Sundown Express', 'True', 'High-Speed Quad'),
('Sunshine Express', 'True', 'High-Speed Quad'),
('Thunderhead Express', 'False', 'High-Speed Quad'),
('Wrangler Carpet', 'False', 'Magic Carpet'),
('Bonanza', 'False', 'Magic Carpet'),
('Buckaroo Carpet', 'False', 'Magic Carpet'),
('Easy Rider', 'False', 'Magic Carpet'),
('Two Whoops 1', 'True', 'Magic Carpet'),
('Two Whoops 2', 'True', 'Magic Carpet');

INSERT INTO steamboat_runs (run_name, open_closed, groomed, difficulty) VALUES
('Alarm Clock', 'False', 'False', '4'),
('Ambush', 'False', 'False', '4'),
('Arc', 'True', 'False', '1'),
('Baby Powder', 'True', 'False', '2'),
('Bail Out', 'False', 'False', '2'),
('Bashor', 'True', 'False', '2'),
('BC Lift Line', 'True', 'False', '4'),
('BC Ski Way', 'True', 'False', '1'),
('Bear Claw', 'False', 'False', '3'),
('Between', 'True', 'False', '2'),
('Betwixt', 'True', 'False', '2'),
('Big Foot', 'True', 'False', '2'),
('Big Meadow', 'True', 'False', '2'),
('Bird''s Beak', 'False', 'False', '5'),
('Biscuits', 'False', 'False', '4'),
('Black Powder', 'False', 'False', '4'),
('Blizzard', 'True', 'False', '2'),
('Boulder Field', 'False', 'False', '5'),
('Boulevard', 'True', 'False', '1'),
('Broadway', 'True', 'False', '1'),
('Buckshot', 'True', 'False', '2'),
('Buddy''s Run', 'True', 'False', '2'),
('Bugs'' Run', 'True', 'False', '4'),
('Cabin Fever', 'False', 'False', '4'),
('Calf Roper', 'True', 'False', '2'),
('Chaps', 'False', 'False', '3'),
('Cheesy Grits', 'False', 'False', '4'),
('Christmas Tree Bowl', 'True', 'False', '5'),
('Chuckwagon', 'True', 'False', '4'),
('Chute 1', 'True', 'False', '5'),
('Chute 2', 'True', 'False', '5'),
('Chute 3', 'True', 'False', '5'),
('Closets', 'True', 'False', '4'),
('Concentration', 'True', 'False', '4'),
('Corridor', 'True', 'False', '4'),
('Cowboy Coffee', 'False', 'False', '2'),
('Crowtrack', 'True', 'False', '4'),
('Cub', 'True', 'False', '2'),
('Cyclone', 'True', 'False', '4'),
('Dawn', 'True', 'False', '4'),
('Daybreak', 'True', 'False', '2'),
('Diamond Hitch', 'False', 'False', '4'),
('Distraction', 'False', 'False', '4'),
('Drop Out', 'True', 'False', '4'),
('Dusk', 'True', 'False', '2'),
('Eagles Nest', 'True', 'False', '2'),
('East Face', 'True', 'False', '5'),
('Eclipse', 'True', 'False', '3'),
('Edge of the World', 'False', 'False', '4'),
('Ego', 'True', 'False', '2'),
('Endless Gully', 'False', 'False', '5'),
('Fairway', 'False', 'False', '4'),
('Fawn', 'True', 'False', '2'),
('Fetcher Glade', 'False', 'False', '4'),
('First Chance', 'True', 'False', '4'),
('Flatout', 'True', 'False', '1'),
('Flintlock', 'True', 'False', '2'),
('Flying Z', 'True', 'False', '4'),
('Flying Z Gulch', 'True', 'False', '3'),
('Fools Gold', 'False', 'False', '4'),
('Four Points Lift Line', 'True', 'False', '4'),
('Frying Pan', 'False', 'False', '4'),
('Giggle Gulch', 'True', 'False', '1'),
('Granola Bowl', 'False', 'False', '5'),
('Gravy', 'False', 'False', '4'),
('Half Hitch', 'False', 'False', '3'),
('Headwall', 'True', 'False', '2'),
('Heavenly Daze', 'True', 'False', '2'),
('Highline', 'True', 'False', '2'),
('High Noon', 'True', 'False', '2'),
('Hot Cakes', 'False', 'False', '4'),
('Huevos', 'False', 'False', '4'),
('Huffman''s', 'True', 'False', '2'),
('Hurricane', 'True', 'False', '4'),
('Jess'' Cut-Off', 'True', 'False', '2'),
('Jump Start', 'False', 'False', '4'),
('Kit', 'True', 'False', '2'),
('Kuus'' Cruise', 'True', 'False', '4'),
('Lariat', 'False', 'False', '2'),
('Last Chance', 'True', 'False', '4'),
('Legends Trees', 'False', 'False', '4'),
('Lightning', 'True', 'False', '2'),
('Lights Out', 'True', 'False', '4'),
('Longhorn', 'False', 'False', '3'),
('Lower Concentration ', 'True', 'False', '2'),
('Lower High Noon', 'True', 'False', '2'),
('Lower Valley View', 'False', 'False', '4'),
('Mahogany Ridge Lift Line', 'False', 'False', '4'),
('Meadow Lane', 'True', 'False', '2'),
('Middle Rib', 'False', 'False', '4'),
('Milk Run', 'False', 'False', '5'),
('Moonlight', 'True', 'False', '2'),
('Morningside Liftline', 'False', 'False', '4'),
('Mother Nature', 'True', 'False', '4'),
('Nash Junction', 'True', 'False', '4'),
('Nelson''s Run', 'True', 'False', '4'),
('No Names', 'True', 'False', '5'),
('Norther', 'True', 'False', '2'),
('North St. Pats', 'True', 'False', '5'),
('Nostrils', 'False', 'False', '5'),
('One O''Clock', 'True', 'False', '2'),
('Oops', 'True', 'False', '4'),
('Outlaw', 'False', 'False', '4'),
('Over Easy', 'True', 'False', '2'),
('Park Lane', 'True', 'False', '1'),
('Perry Park', 'False', 'False', '4'),
('Pony Express Liftline', 'False', 'False', '4'),
('Pressure Drop', 'True', 'False', '4'),
('Pup', 'True', 'False', '2'),
('Quickdraw', 'True', 'False', '2'),
('Rainbow', 'True', 'False', '2'),
('Ramrod', 'True', 'False', '2'),
('Rendezvous Way', 'True', 'False', '1'),
('Right-O-Way', 'True', 'False', '1'),
('Rolex', 'True', 'False', '4'),
('Rooster', 'False', 'False', '2'),
('Rough Rider', 'False', 'False', '1'),
('Rowel', 'True', 'False', '2'),
('Royal Flush', 'False', 'False', '4'),
('Rudi''s Run', 'True', 'False', '2'),
('See Me', 'False', 'False', '4'),
('Shadows', 'True', 'False', '4'),
('Short Cut', 'True', 'False', '1'),
('Sideburn', 'True', 'False', '4'),
('Sitz', 'True', 'False', '2'),
('Sitzback', 'True', 'False', '1'),
('Skeeter''s Run', 'True', 'False', '3'),
('Skidaddle', 'True', 'False', '2'),
('Skyline', 'True', 'False', '2'),
('Snooze Bar', 'False', 'False', '2'),
('South Peak Flats', 'True', 'False', '1'),
('So What', 'True', 'False', '1'),
('Spike', 'True', 'False', '2'),
('Spur Run', 'True', 'False', '1'),
('Stampede', 'True', 'False', '1'),
('Storm Peak Catwalk', 'True', 'False', '4'),
('Storm Peak North', 'True', 'False', '4'),
('Storm Peak South', 'True', 'False', '4'),
('Sundial', 'True', 'False', '1'),
('Sundown Liftline', 'True', 'False', '4'),
('Sunnyside', 'False', 'False', '3'),
('Sunset', 'True', 'False', '3'),
('Sunshine Lift Line', 'True', 'False', '2'),
('Surprise', 'True', 'False', '3'),
('Swinger', 'True', 'False', '1'),
('Ted''s Ridge', 'True', 'False', '4'),
('The Gully', 'True', 'False', '5'),
('The Ridge', 'True', 'False', '4'),
('Thick of It', 'False', 'False', '4'),
('Three O''Clock', 'True', 'False', '4'),
('Tomahawk', 'True', 'False', '1'),
('Tomahawk Face', 'True', 'False', '2'),
('Tornado', 'True', 'False', '4'),
('Tornado Lane', 'True', 'False', '2'),
('Tower', 'True', 'False', '2'),
('Traverse', 'True', 'False', '2'),
('Triangle 3', 'True', 'False', '4'),
('Trick Roper', 'True', 'False', '2'),
('Twilight', 'True', 'False', '4'),
('Twister', 'True', 'False', '4'),
('Two O''Clock', 'True', 'False', '3'),
('Two Step', 'False', 'False', '5'),
('Typhoon', 'True', 'False', '4'),
('Ultimate Glades', 'False', 'False', '5'),
('Vagabond Lower', 'True', 'False', '2'),
('Vagabond Upper', 'True', 'False', '2'),
('Valley View ', 'False', 'False', '4'),
('Velvet', 'True', 'False', '2'),
('Vertigo', 'True', 'False', '4'),
('Vogue', 'True', 'False', '2'),
('Voo Doo', 'True', 'False', '4'),
('Vortex', 'True', 'False', '4'),
('Wake Up Call', 'False', 'False', '4'),
('Wapiti', 'True', 'False', '2'),
('West Side', 'True', 'False', '4'),
('White Out', 'True', 'False', '4'),
('Why Not', 'True', 'False', '1'),
('Wild Blue Way', 'True', 'False', '1'),
('WJW', 'True', 'False', '4'),
('Yoo Hoo', 'True', 'False', '1'),
('Chisholm Trail', 'True', 'False', '0'),
('Duster', 'True', 'False', '0'),
('Lil'' Rodeo Park', 'True', 'False', '0'),
('Maverick''s Half Pipe', 'True', 'False', '0'),
('Rabbit Ears Terrain Park', 'True', 'False', '0'),
('Gate 1', 'True', 'False', '5'),
('Gate 2', 'True', 'False', '5'),
('Gate 3', 'True', 'False', '5'),
('Gate 4', 'True', 'False', '5'),
('Gate 5', 'True', 'False', '5'),
('Gate 6', 'True', 'False', '5'),
('Gate 7', 'True', 'False', '5'),
('Gate 8', 'True', 'False', '5'),
('Hogan Park', 'True', 'False', '5');

INSERT INTO winter_park_lifts (lift_name, open_closed, lift_type) VALUES
('Arrow', 'False', 'Triple Chair'),
('Cabriolet', 'True', 'Cabriolet'),
('Comet', 'True', 'Magic Carpet'),
('Discovery', 'True', 'Double'),
('Endeavour', 'False', 'Triple Chair'),
('Explorer Express', 'True', 'Quad Chair'),
('Gemini Express', 'True', 'Quad Chair'),
('Gondola', 'True', 'Gondola'),
('Hi-Lonesome Express', 'False', 'Quad Chair'),
('Looking Glass', 'True', 'Double'),
('Meteor', 'True', 'Magic Carpet'),
('Olympia Express', 'True', 'Quad Chair'),
('Prospector Express', 'True', 'Quad Chair'),
('Spirit', 'False', 'Magic Carpet'),
('Challenger', 'False', 'Double'),
('Galloping Goose', 'True', 'Double'),
('Iron Horse', 'False', 'Double'),
('Lariat', 'True', 'Rope Tow'),
('Pony Express', 'False', 'Double'),
('Sunnyside Express', 'True', '6 Chair'),
('Super Gauge Express', 'True', '6 Chair'),
('Wild Spur Express', 'False', 'High-Speed 6 Chair'),
('Wild Spur Express Mid-Way Station', 'False', 'High-Speed 6 Chair'),
('Panoramic Express', 'True', '6 Chair'),
('Eagle Wind', 'False', 'Triple Chair'),
('Cirque Sled', 'False', 'Sled');

INSERT INTO winter_park_runs (run_name, open_closed, groomed, difficulty) VALUES
('Allan Phipps', 'True', 'False', '1'),
('Ambush', 'False', 'False', '4'),
('Balch', 'True', 'False', '4'),
('Bill Wilsons Way', 'True', 'False', '1'),
('Bobcat', 'True', 'False', '1'),
('Bradleys Bash', 'True', 'False', '3'),
('Brians Run', 'True', 'False', '4'),
('Butchs Breezeway', 'True', 'False', '2'),
('Cheshire Cat', 'True', 'False', '3'),
('Cranmer', 'True', 'False', '2'),
('Dormouse', 'True', 'False', '1'),
('Easy Way', 'True', 'False', '1'),
('Engeldive', 'True', 'False', '4'),
('High Lonesome Trail', 'True', 'False', '1'),
('Hobo Alley', 'True', 'False', '1'),
('Hook Up', 'True', 'False', '1'),
('Hughes', 'True', 'False', '3'),
('Jabberwocky', 'True', 'False', '2'),
('Jack Kendrick', 'True', 'False', '1'),
('Larry Sale', 'True', 'False', '2'),
('Little Pierre', 'True', 'False', '3'),
('Lonesome Whistle Lower', 'True', 'False', '2'),
('Lonesome Whistle Upper', 'True', 'False', '1'),
('Lower Hughes', 'True', 'False', '3'),
('Lower Parkway', 'True', 'False', '2'),
('Mad Tea Party', 'True', 'False', '1'),
('March Hare', 'True', 'False', '2'),
('March Hare Upper', 'True', 'False', '1'),
('Marmot Flats', 'True', 'False', '1'),
('Mock Turtle', 'True', 'False', '1'),
('Mulligans Mile', 'True', 'False', '4'),
('Norwegian', 'True', 'False', '4'),
('Outrigger Trail', 'True', 'False', '4'),
('Over n Underwood', 'True', 'False', '3'),
('Parkway', 'True', 'False', '1'),
('Porcupine', 'True', 'False', '1'),
('Quick Getaway', 'True', 'False', '2'),
('Rendezvous', 'True', 'False', '2'),
('Rettas Run', 'True', 'False', '4'),
('Ski Papa', 'True', 'False', '1'),
('Sorensen Park', 'True', 'False', '1'),
('Switchyard', 'True', 'False', '1'),
('Turnpike', 'True', 'False', '1'),
('Turnpike - Parkway Bypass', 'True', 'False', '1'),
('Tweedle Dee', 'True', 'False', '2'),
('Tweedle Dum', 'True', 'False', '3'),
('Village Way - Mountain Road', 'True', 'False', '1'),
('Village Way - Parkway Bypass', 'True', 'False', '1'),
('Village Way - Switchyard to Mountain Road', 'True', 'False', '1'),
('Village Way - Tunnel to Parkway', 'True', 'False', '1'),
('Vista Dome', 'True', 'False', '1'),
('Vista Dome Cutoff', 'True', 'False', '3'),
('Whistlestop', 'True', 'False', '1'),
('White Rabbit', 'True', 'False', '2'),
('White Rabbit Lower', 'True', 'False', '1'),
('Arrowhead Loop Lower', 'True', 'False', '2'),
('Arrowhead Loop Upper', 'True', 'False', '4'),
('Awe Chute', 'False', 'False', '5'),
('Baldys Chute', 'False', 'False', '5'),
('Bellmar Bowl', 'True', 'False', '2'),
('Better Not', 'False', 'False', '5'),
('Bluebell', 'True', 'False', '2'),
('Boiler', 'True', 'False', '4'),
('Brakeman', 'True', 'False', '4'),
('Branch Line', 'True', 'False', '4'),
('Cannonball', 'True', 'False', '4'),
('Columbine Lower', 'True', 'False', '4'),
('Columbine Upper', 'True', 'False', '2'),
('Corona Way', 'True', 'False', '2'),
('Corridor Mary Jane to Winter Park', 'True', 'False', '1'),
('Coupler', 'True', 'False', '4'),
('Derailer', 'True', 'False', '4'),
('Drunken Frenchman', 'True', 'False', '4'),
('Edelweiss', 'True', 'False', '2'),
('Freeriders', 'True', 'False', '4'),
('Gandy Dancer', 'True', 'False', '3'),
('Golden Spike', 'True', 'False', '4'),
('Hole in the Wall', 'False', 'False', '5'),
('Iron Horse Trail', 'True', 'False', '4'),
('Jeffs Chute', 'False', 'False', '5'),
('Key Hole', 'False', 'False', '5'),
('Little Ten', 'True', 'False', '4'),
('Long Haul', 'True', 'False', '4'),
('Mary Jane', 'True', 'False', '2'),
('Mary Jane Upper', 'True', 'False', '3'),
('Narrow Gauge', 'True', 'False', '3'),
('Needles Eye', 'True', 'False', '4'),
('Olympia Spur', 'True', 'False', '1'),
('Outhouse', 'True', 'False', '4'),
('Phantom Bridge', 'True', 'False', '4'),
('Pine Cliffs', 'True', 'False', '4'),
('Pony Express Trail', 'True', 'False', '4'),
('Railbender', 'True', 'False', '4'),
('Rainbow Cut', 'True', 'False', '3'),
('Riflesight Notch', 'True', 'False', '4'),
('Rollins Ridge', 'True', 'False', '2'),
('Roundhouse', 'True', 'False', '2'),
('Roundhouse Face', 'True', 'False', '3'),
('Roundhouse Upper', 'True', 'False', '2'),
('Runaway', 'True', 'False', '4'),
('Shoo Fly', 'True', 'False', '1'),
('Short Haul', 'True', 'False', '4'),
('Sidetrack', 'True', 'False', '3'),
('Sleeper', 'True', 'False', '3'),
('Sleepy Hollow', 'True', 'False', '3'),
('Sluice Box', 'True', 'False', '4'),
('Sober Englishman', 'True', 'False', '2'),
('Sterling Way', 'True', 'False', '4'),
('Super Gauge Trail', 'True', 'False', '4'),
('Tie Siding', 'True', 'False', '1'),
('Trestle', 'True', 'False', '4'),
('Village Way - Switchyard', 'True', 'False', '1'),
('Wildwood Glade', 'True', 'False', '2'),
('Aces & Eights', 'False', 'False', '4'),
('Big Valley', 'False', 'False', '1'),
('Buckaroo', 'False', 'False', '2'),
('Chuck Wagon', 'False', 'False', '3'),
('Dilly Dally Alley', 'True', 'False', '2'),
('Gambler', 'False', 'False', '4'),
('Gunbarrel', 'False', 'False', '1'),
('Lower Egress', 'False', 'False', '3'),
('Quickdraw', 'False', 'False', '2'),
('Shootout', 'False', 'False', '2'),
('Stagecoach', 'False', 'False', '2'),
('Sundance', 'False', 'False', '2'),
('Tinhorn', 'False', 'False', '1'),
('Wagon Train', 'False', 'False', '1'),
('Wild Spur Trail Lower', 'False', 'False', '3'),
('Wild Spur Trail Upper', 'False', 'False', '4'),
('Calypso', 'True', 'False', '3'),
('Fireberry Glade', 'True', 'False', '3'),
('Forever Eva', 'True', 'False', '2'),
('Forget-Me-Not', 'True', 'False', '2'),
('Johnstones Junction', 'True', 'False', '3'),
('Juniper', 'True', 'False', '2'),
('Kinnikinnic', 'True', 'False', '3'),
('Larkspur', 'True', 'False', '3'),
('Lupin', 'True', 'False', '3'),
('Paintbrush', 'True', 'False', '2'),
('Parrys Peek', 'True', 'False', '2'),
('Primrose', 'True', 'False', '2'),
('Sky Pilot', 'True', 'False', '3'),
('Village Way - Bowl', 'True', 'False', '2'),
('Willets Way', 'True', 'False', '3'),
('Ashcat', 'True', 'False', '4'),
('Bouncer', 'False', 'False', '4'),
('Gangway', 'True', 'False', '4'),
('Lower Railyard', 'True', 'False', '4'),
('Rail Yard�, including Halfpipe', 'True', 'False', '4'),
('Re-railer', 'True', 'False', '4'),
('Starter Park', 'True', 'False', '4'),
('Belle Fourche', 'False', 'False', '4'),
('Black Coal', 'False', 'False', '4'),
('Eagle Wind', 'False', 'False', '4'),
('Left Hand', 'False', 'False', '4'),
('Little Raven', 'False', 'False', '4'),
('Medicine Man', 'False', 'False', '4'),
('Sharpnose', 'False', 'False', '4'),
('Thunderbird', 'False', 'False', '4'),
('Thunderbird Traverse', 'False', 'False', '4'),
('100s', 'False', 'False', '4'),
('Alphabet Chutes', 'False', 'False', '5'),
('Eldorado', 'False', 'False', '4'),
('Jelly Roll', 'False', 'False', '5'),
('Jelly Roll Glades', 'False', 'False', '4'),
('Rollover', 'False', 'False', '4'),
('Shadow Chute', 'False', 'False', '5'),
('South Basin', 'False', 'False', '4'),
('South Headwall', 'False', 'False', '5'),
('Upper Egress', 'False', 'False', '3'),
('Waterfall', 'False', 'False', '4'),
('West Headwall', 'False', 'False', '5');

